public with sharing class ApplicantHandler {
    //Review Record: As a recruiter, when I advance an applicant to the 'Interviewing' stage, 
    // I need review records to be generated for each interviewer who needs to meet with that applicant.
    // there is an existing position with existing applications in "interview" status, so I will add an existing interview
    // look at appilcations- any in interviewing status we want interview for 
    // need to talk further with this person, advances them to interview status, then 
    // for that one applicant (who we know and is in interviewing), look for position, who interviewer is, and create
    // review records there
    public ApplicantHandler() {

    }
}




